apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-stress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memory-stress
  template:
    metadata:
      labels:
        app: memory-stress
    spec:
      containers:
        - name: stress
          image: polinux/stress
          resources:
            requests:
              memory: "100Mi"
            limits:
              memory: "150Mi"
          command: ["stress"]
          args:
            - "--vm"
            - "1"
            - "--vm-bytes"
            - "200M"
            - "--vm-hang"
            - "1"
